steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - builds
      - submit
      - '--tag'
      - >-
        ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_CLOUD_RUN_PROJECT}:${COMMIT_SHA}
      - .
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - '${_CLOUD_RUN_PROJECT}'
      - >-
        --image=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_CLOUD_RUN_PROJECT}:${COMMIT_SHA}
      - '--region=${LOCATION}'
      - '--platform=managed'
      - '--port=80'
